# Generated by Django 5.0.1 on 2024-02-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='governorate_id',
            new_name='governorate',
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stores.governorate'),
            preserve_default=False,
        ),
    ]
