# Generated by Django 5.0.1 on 2024-02-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_city_name_alter_city_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='governorate',
        ),
    ]
