# Generated by Django 5.0.1 on 2024-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_city_name_ar_governorate_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(max_length=50),
        ),
    ]
