# Generated by Django 4.2.7 on 2024-01-27 11:33

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_distributor_customer'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_doc', models.FileField(upload_to=pathlib.PureWindowsPath('brandApplications/authDocs/%Y/%m/%d'))),
                ('identity_doc', models.FileField(upload_to=pathlib.PureWindowsPath('brandApplications/identityDocs/%Y/%m/%d'))),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.brand')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.distributor')),
            ],
        ),
    ]
