# Generated by Django 5.0.1 on 2024-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_applications', '0003_alter_brandapplication_authorization_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandapplication',
            name='authorization_doc',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='brandapplication',
            name='identity_doc',
            field=models.CharField(max_length=260),
        ),
    ]
