# Generated by Django 5.0.1 on 2024-02-02 11:32

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_applications', '0004_alter_brandapplication_authorization_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandapplication',
            name='authorization_doc',
            field=models.CharField(validators=[common.validators.validate_max_filename_length]),
        ),
        migrations.AlterField(
            model_name='brandapplication',
            name='identity_doc',
            field=models.CharField(validators=[common.validators.validate_max_filename_length]),
        ),
    ]
