# Generated by Django 4.2.15 on 2024-08-31 08:58

import brands_applications.models
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_applications', '0005_alter_brandapplication_authorization_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandapplication',
            name='authorization_doc',
            field=models.FileField(upload_to=brands_applications.models.brand_application_doc_path, validators=[common.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='brandapplication',
            name='identity_doc',
            field=models.FileField(upload_to=brands_applications.models.brand_application_doc_path, validators=[common.validators.validate_file_size]),
        ),
    ]
