# Generated by Django 4.2.13 on 2024-06-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_search_vector_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumitem',
            name='img_url',
            field=models.CharField(),
        ),
    ]
