# Generated by Django 4.2.15 on 2024-08-31 08:57

import common.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_albumitem_img_url_albumitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumitem',
            name='image',
            field=models.ImageField(upload_to=products.models.product_images_path, validators=[common.validators.validate_file_size]),
        ),
    ]
