# Generated by Django 4.2.7 on 2024-01-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_distributor_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BrandDistributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.brand')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.distributor')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='distributors',
            field=models.ManyToManyField(through='brands.BrandDistributors', to='accounts.distributor'),
        ),
        migrations.AddConstraint(
            model_name='branddistributors',
            constraint=models.UniqueConstraint(models.F('brand'), models.F('distributor'), name='brands_distributors'),
        ),
    ]
