# Generated by Django 4.2.7 on 2024-01-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
